# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rbaraglia/pensieve/create_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 372)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.project_name_LE = QtWidgets.QLineEdit(self.groupBox)
        self.project_name_LE.setObjectName("project_name_LE")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.project_name_LE)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.browse_LE = QtWidgets.QLineEdit(self.groupBox)
        self.browse_LE.setReadOnly(True)
        self.browse_LE.setObjectName("browse_LE")
        self.horizontalLayout_2.addWidget(self.browse_LE)
        self.browse_PB = QtWidgets.QPushButton(self.groupBox)
        self.browse_PB.setObjectName("browse_PB")
        self.horizontalLayout_2.addWidget(self.browse_PB)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.speaker_LE = QtWidgets.QLineEdit(self.groupBox)
        self.speaker_LE.setObjectName("speaker_LE")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.speaker_LE)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.language_CB = QtWidgets.QComboBox(self.groupBox)
        self.language_CB.setObjectName("language_CB")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.language_CB)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sample_rate_CoB = QtWidgets.QComboBox(self.groupBox_2)
        self.sample_rate_CoB.setObjectName("sample_rate_CoB")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.sample_rate_CoB.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sample_rate_CoB)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.encoding_CoB = QtWidgets.QComboBox(self.groupBox_2)
        self.encoding_CoB.setObjectName("encoding_CoB")
        self.encoding_CoB.addItem("")
        self.encoding_CoB.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.encoding_CoB)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prefix_LE = QtWidgets.QLineEdit(self.groupBox_2)
        self.prefix_LE.setObjectName("prefix_LE")
        self.horizontalLayout_3.addWidget(self.prefix_LE)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_PB = QtWidgets.QPushButton(Dialog)
        self.cancel_PB.setObjectName("cancel_PB")
        self.horizontalLayout.addWidget(self.cancel_PB)
        self.create_PB = QtWidgets.QPushButton(Dialog)
        self.create_PB.setObjectName("create_PB")
        self.horizontalLayout.addWidget(self.create_PB)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.sample_rate_CoB.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Project Setting"))
        self.label_3.setText(_translate("Dialog", "Project_Name"))
        self.label_4.setText(_translate("Dialog", "Project Location"))
        self.browse_PB.setText(_translate("Dialog", "Browse"))
        self.label_5.setText(_translate("Dialog", "Speaker"))
        self.label_6.setText(_translate("Dialog", "Language"))
        self.groupBox_2.setTitle(_translate("Dialog", "Audio Setting"))
        self.label.setText(_translate("Dialog", "Sampling_rate"))
        self.sample_rate_CoB.setItemText(0, _translate("Dialog", "8000 Hz"))
        self.sample_rate_CoB.setItemText(1, _translate("Dialog", "16000 Hz"))
        self.sample_rate_CoB.setItemText(2, _translate("Dialog", "21000 Hz"))
        self.sample_rate_CoB.setItemText(3, _translate("Dialog", "22050 Hz"))
        self.sample_rate_CoB.setItemText(4, _translate("Dialog", "44100 Hz"))
        self.sample_rate_CoB.setItemText(5, _translate("Dialog", "48000 Hz"))
        self.sample_rate_CoB.setItemText(6, _translate("Dialog", "88200 Hz"))
        self.sample_rate_CoB.setItemText(7, _translate("Dialog", "96000 Hz"))
        self.label_2.setText(_translate("Dialog", "Encoding"))
        self.encoding_CoB.setItemText(0, _translate("Dialog", "2B"))
        self.encoding_CoB.setItemText(1, _translate("Dialog", "4B"))
        self.label_7.setText(_translate("Dialog", "Recording Prefix"))
        self.prefix_LE.setToolTip(_translate("Dialog", "<html><head/><body><p>When sample are recorded they will have the name &lt;choosen_prefix&gt;_XXXXX</p></body></html>"))
        self.label_8.setText(_translate("Dialog", "_XXX.wav"))
        self.cancel_PB.setText(_translate("Dialog", "Cancel"))
        self.create_PB.setText(_translate("Dialog", "Create"))
