# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rbaraglia/pensieve/resume.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.project_name_LE = QtWidgets.QLineEdit(self.groupBox)
        self.project_name_LE.setReadOnly(True)
        self.project_name_LE.setObjectName("project_name_LE")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.project_name_LE)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.speaker_LE = QtWidgets.QLineEdit(self.groupBox)
        self.speaker_LE.setReadOnly(True)
        self.speaker_LE.setObjectName("speaker_LE")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.speaker_LE)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.language_LE = QtWidgets.QLineEdit(self.groupBox)
        self.language_LE.setReadOnly(True)
        self.language_LE.setObjectName("language_LE")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.language_LE)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.sentences_read_SP = QtWidgets.QSpinBox(self.groupBox_2)
        self.sentences_read_SP.setReadOnly(True)
        self.sentences_read_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sentences_read_SP.setMaximum(999999)
        self.sentences_read_SP.setObjectName("sentences_read_SP")
        self.horizontalLayout_2.addWidget(self.sentences_read_SP)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.sentences_total_SP_2 = QtWidgets.QSpinBox(self.groupBox_2)
        self.sentences_total_SP_2.setReadOnly(True)
        self.sentences_total_SP_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sentences_total_SP_2.setMaximum(999999)
        self.sentences_total_SP_2.setObjectName("sentences_total_SP_2")
        self.horizontalLayout_2.addWidget(self.sentences_total_SP_2)
        self.percent_label = QtWidgets.QLabel(self.groupBox_2)
        self.percent_label.setObjectName("percent_label")
        self.horizontalLayout_2.addWidget(self.percent_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.words_read_SP = QtWidgets.QSpinBox(self.groupBox_2)
        self.words_read_SP.setReadOnly(True)
        self.words_read_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.words_read_SP.setMaximum(999999)
        self.words_read_SP.setObjectName("words_read_SP")
        self.horizontalLayout_3.addWidget(self.words_read_SP)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.words_total_SP = QtWidgets.QSpinBox(self.groupBox_2)
        self.words_total_SP.setReadOnly(True)
        self.words_total_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.words_total_SP.setMaximum(999999)
        self.words_total_SP.setObjectName("words_total_SP")
        self.horizontalLayout_3.addWidget(self.words_total_SP)
        self.percent_word_label = QtWidgets.QLabel(self.groupBox_2)
        self.percent_word_label.setObjectName("percent_word_label")
        self.horizontalLayout_3.addWidget(self.percent_word_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.add_text_PB = QtWidgets.QPushButton(self.groupBox_2)
        self.add_text_PB.setObjectName("add_text_PB")
        self.horizontalLayout_4.addWidget(self.add_text_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.n_samples_SP = QtWidgets.QSpinBox(self.groupBox_3)
        self.n_samples_SP.setReadOnly(True)
        self.n_samples_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.n_samples_SP.setMaximum(999999)
        self.n_samples_SP.setObjectName("n_samples_SP")
        self.horizontalLayout_5.addWidget(self.n_samples_SP)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.total_duration_LE = QtWidgets.QLineEdit(self.groupBox_3)
        self.total_duration_LE.setReadOnly(True)
        self.total_duration_LE.setObjectName("total_duration_LE")
        self.horizontalLayout_6.addWidget(self.total_duration_LE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.record_PB = QtWidgets.QPushButton(self.groupBox_3)
        self.record_PB.setObjectName("record_PB")
        self.horizontalLayout_7.addWidget(self.record_PB)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.close_PB = QtWidgets.QPushButton(Form)
        self.close_PB.setObjectName("close_PB")
        self.horizontalLayout.addWidget(self.close_PB)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Project"))
        self.label.setText(_translate("Form", "Project name"))
        self.label_2.setText(_translate("Form", "Speaker"))
        self.label_3.setText(_translate("Form", "Language"))
        self.groupBox_2.setTitle(_translate("Form", "Texts"))
        self.label_4.setText(_translate("Form", "Sentences count"))
        self.label_5.setText(_translate("Form", "/"))
        self.percent_label.setText(_translate("Form", "(0%)"))
        self.label_6.setText(_translate("Form", "Words count"))
        self.label_7.setText(_translate("Form", "/"))
        self.percent_word_label.setText(_translate("Form", "(0%)"))
        self.add_text_PB.setText(_translate("Form", "Add Text"))
        self.groupBox_3.setTitle(_translate("Form", "Audio"))
        self.label_8.setText(_translate("Form", "Sample recorded"))
        self.label_9.setText(_translate("Form", "Total duration"))
        self.record_PB.setText(_translate("Form", "Record"))
        self.close_PB.setText(_translate("Form", "Close Project"))
