# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rbaraglia/pensieve/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 613)
        self.main_window_widget = QtWidgets.QWidget(MainWindow)
        self.main_window_widget.setObjectName("main_window_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_window_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shortcuts_widget = QtWidgets.QWidget(self.main_window_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shortcuts_widget.sizePolicy().hasHeightForWidth())
        self.shortcuts_widget.setSizePolicy(sizePolicy)
        self.shortcuts_widget.setObjectName("shortcuts_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.shortcuts_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_PB = QtWidgets.QPushButton(self.shortcuts_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_PB.sizePolicy().hasHeightForWidth())
        self.home_PB.setSizePolicy(sizePolicy)
        self.home_PB.setMinimumSize(QtCore.QSize(90, 90))
        self.home_PB.setText("")
        self.home_PB.setFlat(True)
        self.home_PB.setObjectName("home_PB")
        self.verticalLayout.addWidget(self.home_PB)
        self.text_PB = QtWidgets.QPushButton(self.shortcuts_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_PB.sizePolicy().hasHeightForWidth())
        self.text_PB.setSizePolicy(sizePolicy)
        self.text_PB.setMinimumSize(QtCore.QSize(90, 90))
        self.text_PB.setText("")
        self.text_PB.setFlat(True)
        self.text_PB.setObjectName("text_PB")
        self.verticalLayout.addWidget(self.text_PB)
        self.record_PB = QtWidgets.QPushButton(self.shortcuts_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record_PB.sizePolicy().hasHeightForWidth())
        self.record_PB.setSizePolicy(sizePolicy)
        self.record_PB.setMinimumSize(QtCore.QSize(90, 90))
        self.record_PB.setText("")
        self.record_PB.setFlat(True)
        self.record_PB.setObjectName("record_PB")
        self.verticalLayout.addWidget(self.record_PB)
        spacerItem = QtWidgets.QSpacerItem(20, 146, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.setting_PB = QtWidgets.QPushButton(self.shortcuts_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_PB.sizePolicy().hasHeightForWidth())
        self.setting_PB.setSizePolicy(sizePolicy)
        self.setting_PB.setMinimumSize(QtCore.QSize(90, 90))
        self.setting_PB.setText("")
        self.setting_PB.setFlat(True)
        self.setting_PB.setObjectName("setting_PB")
        self.verticalLayout.addWidget(self.setting_PB)
        self.horizontalLayout.addWidget(self.shortcuts_widget)
        self.line = QtWidgets.QFrame(self.main_window_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.central_widget = QtWidgets.QWidget(self.main_window_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout.addWidget(self.central_widget)
        MainWindow.setCentralWidget(self.main_window_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vox Harvest"))
