# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rbaraglia/pensieve/texts.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.sentence_count_SP = QtWidgets.QSpinBox(self.groupBox)
        self.sentence_count_SP.setReadOnly(True)
        self.sentence_count_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sentence_count_SP.setObjectName("sentence_count_SP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sentence_count_SP)
        self.word_count_SP = QtWidgets.QSpinBox(self.groupBox)
        self.word_count_SP.setReadOnly(True)
        self.word_count_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.word_count_SP.setObjectName("word_count_SP")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.word_count_SP)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(208, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_formated_PB = QtWidgets.QPushButton(self.groupBox)
        self.add_formated_PB.setObjectName("add_formated_PB")
        self.horizontalLayout.addWidget(self.add_formated_PB)
        self.add_raw_PB = QtWidgets.QPushButton(self.groupBox)
        self.add_raw_PB.setObjectName("add_raw_PB")
        self.horizontalLayout.addWidget(self.add_raw_PB)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.histo_widget = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.histo_widget.sizePolicy().hasHeightForWidth())
        self.histo_widget.setSizePolicy(sizePolicy)
        self.histo_widget.setMinimumSize(QtCore.QSize(0, 150))
        self.histo_widget.setObjectName("histo_widget")
        self.verticalLayout.addWidget(self.histo_widget)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.avg_SP = QtWidgets.QSpinBox(self.groupBox_2)
        self.avg_SP.setReadOnly(True)
        self.avg_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.avg_SP.setObjectName("avg_SP")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.avg_SP)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.min_SP = QtWidgets.QSpinBox(self.groupBox_2)
        self.min_SP.setReadOnly(True)
        self.min_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.min_SP.setObjectName("min_SP")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.min_SP)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.max_SP = QtWidgets.QSpinBox(self.groupBox_2)
        self.max_SP.setReadOnly(True)
        self.max_SP.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.max_SP.setObjectName("max_SP")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_SP)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Project texts"))
        self.label_2.setText(_translate("Form", "Word Count:"))
        self.label.setText(_translate("Form", "Sentence Count:"))
        self.add_formated_PB.setToolTip(_translate("Form", "<html><head/><body><p>Formated text are files where sentences are separated by newlines:</p><p>Hi, how are you ?</p><p>The weather in Paris is nice and warm.</p><p>...</p></body></html>"))
        self.add_formated_PB.setText(_translate("Form", "Add Formated Text"))
        self.add_raw_PB.setText(_translate("Form", "Add Raw Text"))
        self.groupBox_2.setTitle(_translate("Form", "Stats"))
        self.label_3.setText(_translate("Form", "Average words per sentence:"))
        self.label_4.setText(_translate("Form", "Min words per sentence:"))
        self.label_5.setText(_translate("Form", "Max words per sentence:"))
